"""backup_codes

Revision ID: 1ad402661d1f
Revises: 5db5c2f9a622
Create Date: 2024-09-22 15:01:58.930384

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ad402661d1f'
down_revision = '5db5c2f9a622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
