"""backup_codess

Revision ID: 4502442e67af
Revises: 1ad402661d1f
Create Date: 2024-09-22 15:31:00.793050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4502442e67af'
down_revision = '1ad402661d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('backup_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'backup_codes')
    # ### end Alembic commands ###
