"""api_token_enabled2

Revision ID: 759cd70cc68f
Revises: 779fc3cd1f47
Create Date: 2024-09-09 18:58:48.532518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '759cd70cc68f'
down_revision = '779fc3cd1f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
