"""api_token_enabled

Revision ID: 779fc3cd1f47
Revises: a5aa7253b71e
Create Date: 2024-09-09 18:05:04.854585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '779fc3cd1f47'
down_revision = 'a5aa7253b71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
