"""customercontact

Revision ID: 8522acda25e9
Revises: 1ea362cf15a2
Create Date: 2024-05-24 18:09:06.473354

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8522acda25e9'
down_revision = '1ea362cf15a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
