"""added ice, rib to suppliers

Revision ID: 9da1f6b7b9c4
Revises: d54aaed4a69a
Create Date: 2024-06-20 15:28:48.930226

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9da1f6b7b9c4'
down_revision = 'd54aaed4a69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('ice', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('supplier', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('supplier', sa.Column('rib', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'rib')
    op.drop_column('supplier', 'postal_code')
    op.drop_column('supplier', 'ice')
    # ### end Alembic commands ###
