"""api_token
Revision ID: a5aa7253b71e
Revises: 89009d1905d6
Create Date: 2024-09-09 17:18:33.507717
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'a5aa7253b71e'
down_revision = '89009d1905d6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('api_token_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.drop_column('user', 'api_token_enabled')
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###