"""api_token_created_at_

Revision ID: ae04db59faad
Revises: 04efbfb9a89f
Create Date: 2024-09-09 19:54:14.830337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae04db59faad'
down_revision = '04efbfb9a89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
