"""couple mods in payments

Revision ID: bae52a12fa37
Revises: d69d1c772112
Create Date: 2024-06-26 19:28:23.373846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bae52a12fa37'
down_revision = 'd69d1c772112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentfromcustomer', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('paymentfromcustomer', 'amount_euro')
    op.drop_column('paymentfromcustomer', 'amount_mad')
    op.add_column('paymenttosupplier', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('paymenttosupplier', 'amount_euro')
    op.drop_column('paymenttosupplier', 'amount_mad')
    op.alter_column('supplier', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('paymenttosupplier', sa.Column('amount_mad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('paymenttosupplier', sa.Column('amount_euro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('paymenttosupplier', 'amount')
    op.add_column('paymentfromcustomer', sa.Column('amount_mad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('paymentfromcustomer', sa.Column('amount_euro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('paymentfromcustomer', 'amount')
    # ### end Alembic commands ###
