"""api_token_created_at__

Revision ID: c73639e03fc2
Revises: ae04db59faad
Create Date: 2024-09-09 20:02:08.951371

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c73639e03fc2'
down_revision = 'ae04db59faad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
