"""remove amount_in_currency

Revision ID: d54aaed4a69a
Revises: 8522acda25e9
Create Date: 2024-06-19 17:00:53.324486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd54aaed4a69a'
down_revision = '8522acda25e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('externalinvoice', 'amount_in_currency')
    op.drop_column('internalinvoice', 'amount_in_currency')
    op.alter_column('part', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('part', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('internalinvoice', sa.Column('amount_in_currency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('externalinvoice', sa.Column('amount_in_currency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
