"""added ice, rib to customers

Revision ID: d69d1c772112
Revises: 9da1f6b7b9c4
Create Date: 2024-06-20 15:50:02.430944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd69d1c772112'
down_revision = '9da1f6b7b9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('ice', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('customer', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('customer', sa.Column('rib', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'rib')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'ice')
    # ### end Alembic commands ###
