"""Add is_active to Project model

Revision ID: f231057028f2
Revises: 0984f8c40ddf
Create Date: 2024-07-15 16:46:37.691690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f231057028f2'
down_revision = '0984f8c40ddf'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('project', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE project SET is_active = TRUE WHERE is_active IS NULL")
    
    # Now set the column to non-nullable
    op.alter_column('project', 'is_active', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_active')
    # ### end Alembic commands ###
